### ISSUE TITLE
Branch.iO open link on android crashes

### ISSUE THREAD

**Issue by softsan** [BranchMetrics/xamarin-branch-deep-linking#62] opened 2017-08-24 16:48 UTC
Hi,

We integrate Branch.io in our Xamarin.Forms app. It works fine in iOS. But when we click on a SMS link on android, it get crashed with following StackTrace:

`Xamarin caused by: java.lang.OutOfMemoryError: Could not allocate JNI Env
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:730)
	at io.branch.referral.ServerRequestQueue.persist(ServerRequestQueue.java:65)
	at io.branch.referral.ServerRequestQueue.insert(ServerRequestQueue.java:211)
	at io.branch.referral.Branch.insertRequestAtFront(Branch.java:2195)
	at io.branch.referral.Branch.registerInstallOrOpen(Branch.java:2204)
	at io.branch.referral.Branch.registerAppInit(Branch.java:2283)
	at io.branch.referral.Branch.initializeSession(Branch.java:2234)
	at io.branch.referral.Branch.initUserSessionInternal(Branch.java:1238)
	at io.branch.referral.Branch.initSession(Branch.java:895)
	at io.branch.referral.Branch.initSessionWithData(Branch.java:1015)
	at io.branch.referral.Branch.startSession(Branch.java:2478)
	at io.branch.referral.Branch.access$900(Branch.java:75)
	at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityStarted(Branch.java:2419)
	at android.app.Application.dispatchActivityStarted(Application.java:207)
	at android.app.Activity.onStart(Activity.java:1190)
	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:595)
	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.n_onStart(Native Method)
	at md5b60ffeb829f638581ab2bb9b1a7f4f3f.FormsAppCompatActivity.onStart(FormsAppCompatActivity.java:121)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
	at android.app.Activity.performStart(Activity.java:6699)
	at android.app.Activity.performRestart(Activity.java:6773)
	at android.app.ActivityThread.handleSleeping(ActivityThread.java:4035)
	at android.app.ActivityThread.-wrap23(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1663)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6121)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

Any thoughts?

**Comment by antonargunov** [comment] 2017-08-27 15:38
Hi @softsan , sorry for delay.
I can't reproduce that issue in our testbed.
Can you send an example of project where you have that issue?

**Comment by BenBach** [comment] 2018-07-31 19:37
@softsan Did you figure out the issue? Any help highly appreciated

**Comment by csalmi-branch** [comment] 2019-01-17 00:50
@softsan or @BenBach are you still experiencing this issue?

**Comment by csalmi-branch** [comment] 2019-02-28 18:49
Due to the age of this issue, I am closing this now. If you are encountering this problem still, please reach out to our support team (support.branch.io) or open a new github issue and we would be happy to help you out!

**Closed by csalmi-branch** 2019-02-28 18:49 UTC

**Comment by jebberwocky** [comment] 2019-09-28 09:47
Huawei ROM limits the max # of threads can be created. It is more a Huawei ROM issue
