### ISSUE TITLE
Non-Forms Android never gets Branch link parameters

### ISSUE THREAD

**Issue by mlb5000** [BranchMetrics/xamarin-branch-deep-linking#22] opened 2016-04-04 13:39 UTC
I have integrated the Branch Xamarin SDK into my app as described in this documentation (v2.1.0), but for some reason anytime I open one of my short links (e.g. https://bnc.lt/1234/823687kf) where 1234 is the suffix assigned to me an configured as `DataPath` in my `Intent` filter, the dictionary in the `InitSessionComplete` method is always empty. When I create a standard deep link using the URL parameter method everything works OK, but that's probably because it's using my custom URL scheme and not the App Links method. Anything I should look for here?

**Comment by antonargunov** [comment] 2016-04-08 09:22
@mlb5000 Sorry for delay, I have questions:
1) Did you add intent filter as described?
https://github.com/BranchMetrics/Android-Deferred-Deep-Linking-SDK/blob/master/README.md#leverage-android-app-links-for-deep-linking

2) How did you create your link (https://bnc.lt/1234/823687kf)?

**Comment by mlb5000** [comment] 2016-04-08 11:31
@antonargunov yes, the intent filter is like this:

```[IntentFilter(new[] { "android.intent.action.VIEW" }, Categories = new[] { "android.intent.category.DEFAULT", "android.intent.category.BROWSABLE" }, DataScheme = "https", DataHost="bnc.lt", DataPathPrefix = "/mbWm")]```

We create our links on our backend using the Branch HTTP API. `1234` was just an example, obviously any we generate are actually prefixed with `https://bnc.lt/mbWm/`

**Comment by antonargunov** [comment] 2016-04-08 11:57
@mlb5000 
1) Did you enable App Links for Android?
2) Did you register your prefix in Dashboard?

**Comment by mlb5000** [comment] 2016-04-08 12:02
@antonargunov yes, App Links is enabled. I don't see a place to register a prefix on the Dashboard. I put my certificate fingerprint in there and it says `Please be sure to include this in your intent-filter: android:pathPrefix="/mbWm". `

**Comment by antonargunov** [comment] 2016-04-08 12:36
@mlb5000 try please:
- create new link in dashboard (link will be created with prefix)
- try new link

Note:
When I enable App Links and use default prefix (I have no any certificate), my links work ( I create links in Dashboard ).
So, let's try to create new link with your prefix in dashboard and try to use it.

**Comment by antonargunov** [comment] 2016-04-08 12:55
@mlb5000 I am appologise for questioning :), but we need info to reproduce this bug.
Btw, can you write method that you use for link generation (with example data)?

**Comment by mlb5000** [comment] 2016-04-08 13:33
@antonargunov I created a Marketing link using the dashboard. The app recognizes it, but the dictionary passed to InitSessionComplete only has two keys `+is_first_session` and `+clicked_branch_link`, both of which are False.

**Comment by mlb5000** [comment] 2016-04-08 13:39
I do keep seeing this after I send up an event every time. I don't know if `data` here could be overriding my Intent.

```04-08 09:34:26.726 I/BranchSDK(32365): returned {"session_id":"246978404391974152","identity_id":"244117684524978162","device_fingerprint_id":"244117684478878684","browser_fingerprint_id":null,"link":"https://bnc.lt/a/key_live_<removed>?%24identity_id=244117684524978162","identity":"6048","data":"{\"+is_first_session\":false,\"+clicked_branch_link\":false}"}```

**Comment by mlb5000** [comment] 2016-04-08 13:40
Actually, it's not every time I send an event. That's the response to `https://api.branch.io/v1/open`

**Comment by mlb5000** [comment] 2016-04-08 13:56
Note that the device I am testing on is Android 5.1, but I don't think that should make a difference. The OS still understands the intent filter and shows my app in the list for those links, so the SDK should be able to grab the parameters.

**Comment by mlb5000** [comment] 2016-04-08 14:14
I just checked the `Intent` passed to `OnNewIntent` when opening the app using that marketing link. The `DataString` parameter has the deep link as expected, but the `InitSessionComplete` dictionary is still only those two keys and not the custom fields I provided.

**Comment by mlb5000** [comment] 2016-04-08 14:20
I don't actually see any sign in LogCat that the SDK is trying to look up the parameters for the link at all...should I?

**Comment by mlb5000** [comment] 2016-04-08 15:18
I just downgraded to 1.2.1 and even that isn't working.

**Comment by antonargunov** [comment] 2016-04-08 15:38
Wait please I am trying to reproduce your issue.
As I understand, you click link in browser, app opens, but dictionary is empty (or with 2 flags), right?

**Comment by mlb5000** [comment] 2016-04-08 15:41
@antonargunov yes, that is all.

**Comment by mlb5000** [comment] 2016-04-08 16:21
@antonargunov if I close the app completely and open it using the deep link it works (as an app link), but if the app is already running the new parameters are not retrieved. Using 1.2.1, and I am callING `SetNewUrl` in `OnNewIntent`

**Comment by antonargunov** [comment] 2016-04-08 16:36
@mlb5000 can you download from github full SDK v.2.1.0 with our TestBed and try Android TestBed (with your changes for App Links, with your key and bundle id)? Use please link that you created in Dashboard.
Really, I don't understand what is happens, because all works for me.

Note: use please v2.1.0, don't use v1.2.x

**Comment by mlb5000** [comment] 2016-04-08 18:00
@antonargunov Doesn't work in the test bed app either. The only parameters that show up in latest params are the two I mentioned.

Upgrading from 1.2.1 to 2.1.0 the app doesn't even fetch deep link parameters when opened from the background. At least 1.2.1 did that. Neither retrieve new parameters when the app is reactivated from the background using a new Intent.

**Comment by mlb5000** [comment] 2016-04-08 18:17
@antonargunov Confirmed. After adding my key to `MainActivity.cs` and changing the package ID to match the app showed `+is_first_session: True` the first time. Then I sent the app to the background and opened the deep link. The app launched and that changed to `False`. However, none of the Deep Link Data I configured on that link are pulled in, which is kind of the whole point.

**Comment by h15ter** [comment] 2016-05-06 13:04
@antonargunov I experience EXACTLY the same issue as the one @mlb5000 described. I keep clicking the same deep link, no matter how it's created, if it's persistent or not etc - I'm 100% confident link is correct. Sometimes there is link data available in OnInitComplete, sometimes it's not. 

I see same stuff in logcat: sometimes there is a "good" json response with link data from https://api.branch.io/v1/open, sometimes it's "bad" and only has two keys +is_first_session and +clicked_branch_link, both of which are False.

There is no real pattern - there might be 3 or 4 successful attempts, then a few "no-data" ones, then a few "good" ones again.

@antonargunov, it's a month since the issue is first reported. Do you have any fix or is there any workaround? Do you need any extra information from logcat/debug session?

**Comment by mlb5000** [comment] 2016-05-06 13:07
@h15ter I haven't heard anything from them in weeks. Even their iOS SDK does this sometimes, which is disappointing since it's completely useless without retrieving the parameters.

**Comment by h15ter** [comment] 2016-05-06 13:24
@antonargunov 
Here are screenshots from the debug session and meaningful logcat logs for a few sequential deep link attempts:
![bad](https://cloud.githubusercontent.com/assets/5887224/15074319/f7372a32-13a6-11e6-8db8-1ebde20defb1.png)
![good](https://cloud.githubusercontent.com/assets/5887224/15074320/f7375ee4-13a6-11e6-87b7-777d1aea5249.png)
[logcat.txt](https://github.com/BranchMetrics/Xamarin-Deferred-Deep-Linking-SDK/files/252281/logcat.txt)

**Comment by antonargunov** [comment] 2016-05-06 16:06
Hi guys, I am preparing new version of Xamarin SDK with updated native libs.
Wait please until I will finish new version. I think new version will be made next week.

**Comment by h15ter** [comment] 2016-05-06 20:01
@antonargunov 
So is it a known problem of old native libs? Could you please give me a link to the issue registered for native sdk so I could contact guys developing it for details?

Do you know what exactly goes wrong, what makes you think that the problem will be solved after you update native libs? I'm just trying to understand if it's just an assumption or proved fact based on some investigation...

I don't want to look rude, please understand. I see a month-old issue with no progress at all, no details from developer etc. We already spent quite a few time trying to integrate Branch.io with our product, and we don't feel it's reliable enough, so I'm a bit skeptical about the idea to just cross fingers and wait.   I'd like to get some real help now.

**Comment by antonargunov** [comment] 2016-05-06 21:29
@h15ter 
1) we could not to reproduce this issue in our TestBed
2) we discussed with Matthew via e-mail, and we tried his links and branch key - all worked, and we sent him our logs
3) we didn't receive his test project, but project as I understood with several activities
4) we can't imagine what architecture of app you have, what and where and how you call
5) we even don't know how you set Branch parameters in your app
6) we don't know what parameters you use when you generate links
7) etc.

So, the best way:
1) wait until I will finish new version
2) if issue will occur - send your test project where we will be able to reproduce this issue

Right now, you can ping our support team and send test project,
or ping our support team and we can work with you more closer via skype.

We want to fix the issue asap, but right now we have no real additional info.

**Comment by h15ter** [comment] 2016-05-06 22:11
@antonargunov
I've posted logcat logs, it's clear that Branch API returns no data. There are timestamps, keys, session IDs and other parameters - should be enough to start investigation, right?
I can provide the link and other details, what do you need?

If you can't investigate the issue without app now, what will happen if something will stop working later, when we go live with Branch? Would you also demand us to send source code of our production/live app to begin investigation? :)

**Comment by antonargunov** [comment] 2016-05-06 23:59
@h15ter 
>>If you can't investigate the issue without app now, what will happen if something will stop working later, when we go live with Branch?

Investigate what?

I can see in your log:
- request was sent
- response was returned
- in first case you had "+clicked_branch_link:true", it means for me - you clicked a link and you received "deeplinkselfcompleteserver", "deeplinkselfcompletetoken", "+referrer" (as I understand deeplinkselfcompleteserver and deeplinkselfcompletetoken are metadata parameters)
- in second case you had "+clicked_branch_link:false" it means for me - you opened app without clicking any links
- third case is the same like first case

For me - all works.

I don't know what did you do, can you write detailed steps for reproducing?
Did you try to reproduce this issue with our TestBed? If no, can you try?

**Comment by h15ter** [comment] 2016-05-07 06:57
@antonargunov
Yes, I'll try your TestBed later.

Here is what I do with my app:
1) I generate link in browser by sending post request to your public API
2) I pass no extra parameters, only my deep link data
3) I immediately validate the link with get request to your public API, and I see it's valid and has data attached
4) I also tried to use persistent link (created from dashboard) instead
5) Once link is created, I add it to my HTML, so user can click it
6) When I click the link, app launches (or resumes)
7) OnInitComplete hits, and it either has link data available or not
8) I switch back to the browser and click the same link again
9) I repeat steps 7-8 multiple times, and this is the way how requests are logged
10) The issue is about data not consistently available on step 7
11) It doesn't really matter if I keep clicking exactly the same link from the same page, or different ones, if I refresh page or not etc.

**Comment by mlb5000** [comment] 2016-05-08 17:10
@h15ter as another data point. Is your app Forms or non-Forms?

**Comment by antonargunov** [comment] 2016-05-11 21:13
Hi guys, I have committed new version of Xamarin SDK with updated native libs.
Try please.
You can download new package from github and update from local source or wait until we upload it to nuget.org

**Comment by antonargunov** [comment] 2016-05-12 12:23
Guys, we have uploaded new package to nuget.org

**Comment by mlb5000** [comment] 2016-05-12 14:24
I upgraded the package but it still never realizes that the Intent was launched with a Branch link: `+clicked_branch_link:false`. I even changed the code to initialize the framework using `Application` and calling `GetInstance().InitSession(this)` in my Activity's `OnResume` and `OnCreate`, but still nothing. It doesn't even work some of the time, and logcat shows no hint that the framework even realized the app was launched with a link.

**Comment by antonargunov** [comment] 2016-05-12 15:50
@mlb5000 I have sent an e-mail

**Comment by antonargunov** [comment] 2016-11-01 17:35
We have uploaded new version of Xamarin SDK.
You can find samples for iOS and Android (form, non-form) in our repo.

**Closed by antonargunov** 2016-11-01 17:35 UTC
